### PR TITLE
Detect compiler

### PR DESCRIPTION
**Pull request by Victor-Savu**
Implementation of #73

### CODE REVIEW

**Comment by somini** [comment]
This supersedes #183

**Comment by Victor-Savu** [comment]
Is this useful? Should it be merged? Is there anything that I should add (e.g. documentation)?

**Comment by aserebryakov** [comment]
@Victor-Savu Does it work if I open vim from e.g. `src` directory?

**Comment by Victor-Savu** [comment]
Yes, it looks up the tree for the Cargo.toml file.

**Pull request merged**
