### PR TITLE
Add new keywords

### PR DESCRIPTION
**Pull request by hcpl**
* `async` from https://github.com/rust-lang/rfcs/pull/2394;
* `existential` from https://github.com/rust-lang/rfcs/pull/2071.

### CODE REVIEW

**Comment by hcpl** [comment]
cc @da-x

**Comment by hcpl** [comment]
Hi, @da-x!

> `existential` is a weak keyword, meaning it has special meaning only in specific contexts. In other contexts it can be a valid variable name.

I didn't know this was a thing. I searched for places where "`existential` is a weak keyword" was mentioned in https://github.com/rust-lang/rust and https://github.com/rust-lang/rfcs, but couldn't find any. Could you provide the source?

**Comment by da-x** [comment]
@hcpl: https://github.com/rust-lang/rust/blob/abe19a730576cf7ead1bf7995271b53d551ea37f/src/libsyntax_pos/symbol.rs#L417

**Comment by da-x** [comment]
Thanks!

**Pull request merged**
