### PR TITLE
Integrate changes from downstream vim

### PR DESCRIPTION
**Pull request by kejadlen**
As requested in https://www.reddit.com/r/rust/comments/690iup/is_rustlangrustvim_maintained_pull_requests/dh2snv8/. I *think* it's correct, as far as I can tell. Not sure what's up with `syntax/rust.vim`, though.

### CODE REVIEW

**Comment by chetgurevitch** [comment]
Could someone take a look at this?

**Comment by steveklabnik** [comment]
Let's do it. Thank you.

**Comment by chris-morgan** [comment]
There are two functional changes in this, and they both confuse and surprise me:

- `after/syntax/rust.vim`: … what? This is a mistake. If upstream really has it like that, we need to fix it.
- `<`/`>` %-matching (matchpairs) got removed. #160 covers this. We’ll need to investigate why this was done also.

**Comment by kejadlen** [comment]
For reference, upstream [after/syntax/rust.vim](https://github.com/rust-lang/rust.vim/blob/master/after/syntax/rust.vim) and a [ftplugin/rust.vim](https://github.com/vim/vim/blob/master/runtime/ftplugin/rust.vim), which is where `matchpairs` got lost.

Might be easier to look at the [diff for this PR w/the whitespace elided](https://github.com/rust-lang/rust.vim/pull/152/files?w=1).

**Pull request merged**
