### PR TITLE
Add reserved keyword `proc`

### PR DESCRIPTION
**Pull request by ordovicia**
This PR adds `proc` to `rustReservedKeyword`.

### CODE REVIEW

**Comment by ordovicia** [comment]
Ping?

**Comment by ordovicia** [comment]
`yield` is already added to `rustKeyword` [here](https://github.com/rust-lang/rust.vim/blob/b6d88adcf9867aa69f4d20d45d49bb54979842a4/syntax/rust.vim#L36) as well as `macro` and `box`.

I'm not sure they should be registered as `rustReservedKeyword`.
They are in "reserved keywords" list in [book](https://doc.rust-lang.org/book/second-edition/appendix-01-keywords.html) but can be used in nightly (unless I'm misunderstanding).

**Comment by pickfire** [comment]
@ordovicia It's true that it's nightly-only but it's experimental right? My fault that I didn't check deeper since the docs showed that it belong to "Keywords Reserved for Future Use".

**Comment by ordovicia** [comment]
@pickfire Right. `yield`, `macro`, and `box` are all currently experimental (`proc` is not available even in nightly TMK).
@steveklabnik How do you think? Should these keywords belong to `rustReservedKeyword`?

**Comment by ordovicia** [comment]
The `proc` keyword is going to be removed from the reserved keywords list (rust-lang/rust#49699).

**Comment by ordovicia** [comment]
Closing this PR since the `proc` keyword has been removed.
IMHO other keywords e.g. `yield` should be discussed in a separate issue.

**Pull request closed without merging**
