### PR TITLE
Correct check for rustfmt_autosave_if_config_present

### PR DESCRIPTION
**Pull request by DoumanAsh**
It still doesn't help me to prevent rustfmt from running though so I just turned all auto runs on save

### CODE REVIEW

**Comment by da-x** [comment]
I don't think this is the correct fix. Did you reload Vim or the buffers after changing `g:rustfmt_autosave_if_config_present`? If not, there's an alternative fix.

**Comment by DoumanAsh** [comment]
I'm not sure I follow the code very well.

Butt currently my .vimrc has:

```
let g:rustfmt_autosave = 0
let g:rustfmt_autosave_if_config_present = 0
let g:rustfmt_autosave_because_of_config = 0
```

And it was running rustfmt anyway. 
And yes I did even restart vim.

Right now I just removed rustfmt code completely because I don't use it, but as of now I have no idea where and why it runs rustfmt

**Comment by DoumanAsh** [comment]
Re-checking it once, again, it does indeed makes no difference.
So for now I just remove this rustfmt completely and use local fork

**Comment by da-x** [comment]
I tested with these three config lines without reproducing the issue.

BTW the `let g:rustfmt_autosave_because_of_config = 0` line should not be there, as it's not really a global variable to be changed. There is indeed a problem if `g:rustfmt_autosave_if_config_present` is  changed without reloading Vim and I'm fixing that.

**Pull request closed without merging**
