### PR TITLE
Add support for the yield keyword.

### PR DESCRIPTION
**Pull request by phaazon**
Rust has generators now!

### CODE REVIEW

**Comment by chris-morgan** [comment]
Need to remove `yield` from `rustReservedKeyword` too.

**Comment by phaazon** [comment]
Oh I didn’t see.

**Comment by phaazon** [comment]
It should be okay now! :)

**Comment by phaazon** [comment]
Ping? :)

**Comment by michael-zapata** [comment]
Friendly ping as well, I'd love to see this! It also solves #170.

**Pull request merged**
