### PR TITLE
autodetect Cargo.toml filetype as cfg

### PR DESCRIPTION
**Pull request by hrls**
Some highlighting at least

### CODE REVIEW

**Comment by da-x** [comment]
Any reason why `cfg` is better than using [vim-toml](https://github.com/cespare/vim-toml)? I think we should at least make this optional, right? So it would not conflict with `vim-toml`.

**Comment by hrls** [comment]
@da-x `cfg` isn't better than `vim-toml`. Its just for some kind of highlighting without any additional vim plugins.

**Comment by chris-morgan** [comment]
I have a suggestion:

```vim
au BufRead,BufNewFile Cargo.toml if &ft == "" | set filetype=cfg | endif
```

That way, if something else has already set a filetype (e.g. if vim-toml is earlier in the runtimepath), it will leave it alone, but if nothing has (e.g. if vim-toml is later in the runtimepath or missing) it will set it to cfg; vim-toml will then just clobber that with toml, and everyone will be happy.

**Comment by da-x** [comment]
@chris-morgan - very good suggestion :) I tested just now with `vim-toml` on/off before/after, seems to work. @hrls can you please make this fix?

**Comment by hrls** [comment]
@chris-morgan Thanks!
@da-x Sure, done.

**Comment by da-x** [comment]
Thanks!

**Pull request merged**
