### PR TITLE
added cargo command

### PR DESCRIPTION
**Pull request by roberbnd**
The cargo command 
:Cargo
Cbuild
Cclean
Cdoc
Cnew -> creates the project and goes inside
Cinit
Crun
Ctest
Cbench
Cupdate
Csearch  
Cpublish 
Cinstall

### CODE REVIEW

**Comment by steveklabnik** [comment]
because i'm terrible at vimscript, what does this do that https://github.com/rust-lang/rust.vim/blob/master/compiler/cargo.vim doesn't already give us?

**Comment by roberbnd** [comment]
be supposed to  is use to compile the code but I never I found where is use it, if you want to use the folder "compiler"  is with the command :compiler and I  can't found it. The compilation is with 
`
let output = s:system(pwd, shellescape(rustc) . " " . join(map(rustc_args, 'shellescape(v:val)')))
`
line 69 of autoload/rust.vim
another hand my idea is create a interface to cargo like [fugiteve](https://github.com/tpope/vim-fugitive) to Git
now you can execute any command of cargo without leave vim, now is basic (you can supply with :!cargo args ) but in the future we can add more features

**Comment by grawlinson** [comment]
I would love if this made it into rust.vim.

What's delaying the merge?

**Comment by steveklabnik** [comment]
> What's delaying the merge?

https://github.com/rust-lang/rust.vim/issues/148 is delaying everything at the moment.

**Comment by steveklabnik** [comment]
Let's do this

Sorry about the wait.

**Pull request merged**
