### PR TITLE
added UltiSnips

### PR DESCRIPTION
**Pull request by roberbnd**
Hallo
I used the code of vim-go
https://github.com/fatih/vim-go/blob/master/ftplugin/go/snippets.vim
I wonder if it possible add snippets of ultisnips to create the rest of snippets.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'm not sure about this patch; it's not clear that this is something we'd want for everyone...

**Comment by roberbnd** [comment]
just who use Ultisnippts, its ok we can wait if someone is agree or not

**Comment by steveklabnik** [comment]
It seems that nobody else desires this a ton, so I'm going to close it. Thanks!

**Comment by onionjake** [comment]
I wouldn't mind this (sorry so late).

This repo also has some rust ultisnips: https://github.com/honza/vim-snippets/blob/master/UltiSnips/rust.snippets  @roberbnd maybe that would be a better spot?

**Pull request closed without merging**
