### PR TITLE
Don't set formatoptions

### PR DESCRIPTION
**Pull request by george-b**
These are a matter of user preference.

### CODE REVIEW

**Comment by da-x** [comment]
Meddling with `formatoptions` is done by the majority (63%) of other filetypes bundled with Vim. Please provide more information in support of this?

**Comment by george-b** [comment]
Yup, whilst lots of them do this I don't think it's something that should be perpetuated. I [raised this in the main Vim repo](https://github.com/vim/vim/issues/5406) and Bram suggested I contact individual maintainers. This is my first report of such so I'm very much testing the waters here.

**Comment by da-x** [comment]
Per the discussion in #105, looked more into this, and I think `rust.vim` provides a better default than Vim for this option. If you want to override it, please use an `after/ftplugin/rust.vim` file. I see that Bram also hinted at that.

**Comment by george-b** [comment]
I agree with filetypes touching indentation and tab settings as those are pertinent.

My view is this that the behaviours `formatoptions` defines for certain interactions is a user preference. I'd imagine one would want to be consistent across all filetypes, without having to add configuration.

For what it's worth I have the following in my config to ensure such consistency for all filetypes. But I certainly consider it a hack.

```
augroup FormatOptions
  autocmd!
  autocmd FileType * let &l:formatoptions = &g:formatoptions
augroup END
``` 

If this removing the setting of `formatoptions` isn't of interest feel free to close this.

**Comment by da-x** [comment]
We'll keep it then. It also may be one of those things is too late to remove without causing a bit of disruption.

**Pull request closed without merging**
